// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUhHifip3yS4I-eJ-R16iKTDOGeHGLgo',
    appId: '1:527439404993:web:f3bc49717d3cc3e1591940',
    messagingSenderId: '527439404993',
    projectId: 'controlcash-bbb1f',
    authDomain: 'controlcash-bbb1f.firebaseapp.com',
    storageBucket: 'controlcash-bbb1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr4V46Z70HaK-Ofx0kuLHY4JsoJEgexh0',
    appId: '1:527439404993:android:08bc973dc146c026591940',
    messagingSenderId: '527439404993',
    projectId: 'controlcash-bbb1f',
    storageBucket: 'controlcash-bbb1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXSWMM4RTjNHcl0qVP0ffqYyM39hxxbD8',
    appId: '1:527439404993:ios:9905022eed3a0274591940',
    messagingSenderId: '527439404993',
    projectId: 'controlcash-bbb1f',
    storageBucket: 'controlcash-bbb1f.appspot.com',
    iosBundleId: 'com.example.mockups',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXSWMM4RTjNHcl0qVP0ffqYyM39hxxbD8',
    appId: '1:527439404993:ios:9905022eed3a0274591940',
    messagingSenderId: '527439404993',
    projectId: 'controlcash-bbb1f',
    storageBucket: 'controlcash-bbb1f.appspot.com',
    iosBundleId: 'com.example.mockups',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkUhHifip3yS4I-eJ-R16iKTDOGeHGLgo',
    appId: '1:527439404993:web:83a7ffdd30643994591940',
    messagingSenderId: '527439404993',
    projectId: 'controlcash-bbb1f',
    authDomain: 'controlcash-bbb1f.firebaseapp.com',
    storageBucket: 'controlcash-bbb1f.appspot.com',
  );
}
